apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springproject
  name: springproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springproject
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springproject
    spec:
      containers:
      - image: abdulganiu123/springboot:latest
        name: springboot
        ports:
        - containerPort: 8080  
        resources: {}
status: {}
